"""add_possibly_questions_to_document_chunks

Revision ID: 8c5add0dd1a8
Revises: 934e4372c360
Create Date: 2026-02-26 01:44:42.522271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c5add0dd1a8'
down_revision: Union[str, None] = '934e4372c360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('possibly_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('document_chunks', sa.Column('possibly_question_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'possibly_question_embedding')
    op.drop_column('document_chunks', 'possibly_questions')
    # ### end Alembic commands ###
